// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// IMPORTANT: This is a placeholder file. You need to run:
/// ```bash
/// flutterfire configure
/// ```
/// to generate the actual configuration with your Firebase project details.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOU0z7Lz2oK9kH55Xw9bPpsbtKksVYnu8',
    appId: '1:878209621424:android:6629e3ac00510b04100a75',
    messagingSenderId: '878209621424',
    projectId: 'hirefy-eb833',
    storageBucket: 'hirefy-eb833.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9-cGt2ofUDzpDiAN8aJ3kKQ_BxfW1c9E',
    appId: '1:878209621424:ios:03ef00a4fd5de20b100a75',
    messagingSenderId: '878209621424',
    projectId: 'hirefy-eb833',
    storageBucket: 'hirefy-eb833.firebasestorage.app',
    iosBundleId: 'careers.hirefy.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUbabNiPXCGiYJSEzaQ_FTEVgpE97yvtw',
    appId: '1:878209621424:web:d3687a6cdc9d32a9100a75',
    messagingSenderId: '878209621424',
    projectId: 'hirefy-eb833',
    authDomain: 'hirefy-eb833.firebaseapp.com',
    storageBucket: 'hirefy-eb833.firebasestorage.app',
    measurementId: 'G-XTVX7B99SX',
  );
}
